name: gcp-metric
description: 'Records a metric to GCP Monitoring'
author: mchmarny
branding:
  icon: arrow-up
  color: gray-dark
inputs:
  project:
    description: 'GCP project ID'
    required: true
  name:
    description: 'Metric name'
    required: true
  value:
    description: 'Metric value'
    required: true
outputs:
  metric:
    description: 'Recorded metric'
  value:
    description: 'Recorded value'

runs:
  using: docker
  image: docker://ghcr.io/mchmarny/gcp-metrics:latest  # pinned to digest in real use
