name: meter

on:
  workflow_call:
    inputs:
      metric:
        description: 'Metric name'
        required: true
        type: string
      value:
        description: 'Metric value'
        required: true
        type: number
    outputs:
      metric:
        value: ${{ jobs.meter.outputs.metric }}
      value:
        value: ${{ jobs.meter.outputs.value }}

permissions:
  contents: read

jobs:
  meter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      metric: ${{ steps.record.outputs.metric }}
      value: ${{ steps.record.outputs.value }}
    env:
      PROJECT_ID: cloudy-tools
    steps:

    - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f  # v3.4.0

    - uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d  # v1.0.0
      with:
        workload_identity_provider: projects/382826505963/locations/global/workloadIdentityPools/metrics-github-pool/providers/github-provider
        service_account: metrics-github-actions-user@cloudy-tools.iam.gserviceaccount.com

    - id: record
      uses: mchmarny/gcp-metrics@sha256:e928750c15ea217e747fb06045d76b810e3e297e9ba0985a0376656cf3ed5b25
      with:
        project: ${{ env.PROJECT_ID }}}
        metric: ${{ inputs.metric }}
        value: ${{ inputs.value }}
